### ISSUE TITLE
BUG: Delete pods after job completion

### ISSUE THREAD

**Issue by odesenfans** [LamaAni/KubernetesJobOperator#28]
Hello again,

I nearly have a working job workflow. One problem I have left is that completed/failed pods are not cleaned up according to the `JobRunnerDeletePolicy` I use.

Simply put, when using `JobRunnerDeletePolicy.IfSucceeded`, the job is properly deleted but my pods are still present, in the `Completed` state. I would like for the operator to clean up my pods as well once the job is done. Of course this should depend on the clean up policy, it's useful to be able to inspect pods for failed job runs.

Thanks, and sorry for my many requests :)

**Comment by odesenfans** [comment]
I realized that this works out of the box when specifying the finalizers field in metadata:

```
apiVersion: batch/v1
kind: Job
metadata:
  finalizers:
    - foregroundDeletion
```

At this point, I wonder:
1. Should this be the default behaviour for this operator? Ex: finalizers are not specified -> default to foreground deletion ?
2. Other option, add some documentation on this topic and call it a day?

**Comment by LamaAni** [comment]
Hi, this should be already happening. Notice in the operator help,

```
        Added yaml values:

            metadata.finalizers += foregroundDeletion
```

Location in code, https://github.com/LamaAni/KubernetesJobOperator/blob/07ce84d61f4fef20d7fdb29b1c7a0f55b1a77bbf/airflow_kubernetes_job_operator/job_runner.py#L168

If this is not happening then it's a bug. Can you please post your Job yaml? This feature is working in my cluster.

**Comment by odesenfans** [comment]
Just tried, on a Kubernetes v1.17.4 cluster:

This works:
```
apiVersion: batch/v1
kind: Job
metadata:
  finalizers:
    - foregroundDeletion
```

This doesn't delete pods.
```
apiVersion: batch/v1
kind: Job
#metadata:
#  finalizers:
#    - foregroundDeletion
```

**Comment by LamaAni** [comment]
There was a bug there.
Will send a PR soon.

**Comment by LamaAni** [comment]
Please see PR: https://github.com/LamaAni/KubernetesJobOperator/pull/29

**Comment by LamaAni** [comment]
Hi, been a while. If you can add a testimonial, that would be fantastic. Here: #40
