### ISSUE TITLE
Is KubernetesJobOperator compatible with Apache Airflow  >= v2.0?

### ISSUE THREAD

**Issue by carlosliarte** [LamaAni/KubernetesJobOperator#43]
### In short:

I would like to upgrade my MWAA environment to Apache Airflow 2.0.2 but there are some incompatibilities between KubernetesJobOperator and new version of providers on the imports of the operator.

### More information

Let me show you an image about the errors.

![image](https://user-images.githubusercontent.com/14752903/120455705-47f95c80-c395-11eb-8b31-bfb639ea0b4c.png)

**Comment by LamaAni** [comment]
Hi, It seems that the base operator is both a different path and has different event calls. I will upgrade this soon and add a PR. Could you test this on your end? (May take a few days)

**Comment by carlosliarte** [comment]
Hi, I don't know how can I test in my end those changes before you upload a new version.

**Comment by LamaAni** [comment]
I'll send instructions. Where are you running airflow? Is it a local machine?

**Comment by carlosliarte** [comment]
I've got an Airflow on my local machine to test but I upload changes to MWAA on AWS.

**Comment by LamaAni** [comment]
Please see correction PR here: https://github.com/LamaAni/KubernetesJobOperator/pull/44/files

To install from the PR branch: 
```shell
pip install git+https://github.com/LamaAni/KubernetesJobOperator@airflow_2_support
```

OR from any branch
```shell
pip install git+https://github.com/LamaAni/KubernetesJobOperator@[ branch name ]
```

Once validated on local on your end I'll merge the PR and do a release.

**Comment by carlosliarte** [comment]
Hi, could you explain me how can I dowload that changes on dockerized airflow to test it?

**Comment by LamaAni** [comment]
You need to create your own airflow image, and then install the change. If you are using an image as a base

```dockerfile
FROM [base image]

USER root
RUN pip install git+https://github.com/LamaAni/KubernetesJobOperator@airflow_2_support

USER airflow # or the default user for the airflow.
```

But it would be enough that you test it locally and then continue.

**Comment by carlosliarte** [comment]
It works perfectly without any errors on dependencies.

**Comment by LamaAni** [comment]
Nice. Tnx. I'll merge and release.

**Comment by LamaAni** [comment]
Please see release here: https://github.com/LamaAni/KubernetesJobOperator/releases/tag/2.0.0
Also, please close this PR if everything is working.

If possible, please star the repo and add a testimonial on your usage of the repo [here](https://github.com/LamaAni/KubernetesJobOperator/issues/40)
