### ISSUE TITLE
Investigate warnings

### ISSUE THREAD

**Issue by brandonruhl** [LamaAni/KubernetesJobOperator#48]
**Describe the bug**
│ [2021-08-03 22:14:52,663[] WARNING - /usr/local/lib/python3.8/dist-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:26 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1Volume`.                                                                                                               │
│ [2021-08-03 22:14:52,665[] WARNING - /usr/local/lib/python3.8/dist-packages/airflow/providers/cncf/kubernetes/backcompat/backwards_compat_converters.py:27 DeprecationWarning: This module is deprecated. Please use `kubernetes.client.models.V1VolumeMount`.  

**To Reproduce**
Look at scheduler logs

**Expected behavior**
should not see warnings

**Comment by brandonruhl** [comment]
Also seeing this 
WARNING - /usr/local/lib/python3.8/dist-packages/airflow_kubernetes_job_operator/kubernetes_job_operator.py:43 DeprecationWarning: This decorator is deprecated.                                                                                                                                                                                     ││ In previous versions, all subclasses of BaseOperator must use apply_default decorator for the`default_args` feature to work properly.                                                                                                                                                                                                                                           ││ In current version, it is optional. The decorator is applied automatically using the metaclass.

**Comment by LamaAni** [comment]
Hi Brandon. Tnx. PR to come.

**Comment by LamaAni** [comment]
Issue fixed in pr: https://github.com/LamaAni/KubernetesJobOperator/pull/49
