### ISSUE TITLE
Namespace resolution failed

### ISSUE THREAD

**Issue by Blokje5** [LamaAni/KubernetesJobOperator#7]
**Describe the bug**
Trying a simple batch job using docker-desktop failed with the following error:

```
ERROR - ('Namespace was not provided in yaml and auto namespace resolution failed.', Exception('Could not resolve current namespace, you must provide a namespace or a context file', TypeError("argument of type 'NoneType' is not iterable")))
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/airflow_kubernetes_job_operator/job_runner.py", line 81, in get_current_namespace
    contexts, active_context = kubernetes.config.list_kube_config_contexts()
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 621, in list_kube_config_contexts
    loader = _get_kube_config_loader_for_yaml_file(config_file)
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 613, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 173, in set_active_context
    context_name = self._config['current-context']
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 495, in __getitem__
    v = self.safe_get(key)
  File "/usr/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 491, in safe_get
    key in self.value):
TypeError: argument of type 'NoneType' is not iterable
```

Task configuration:
```
job_task=KubernetesJobOperator(
    task_id="test-job",
    dag=dag,
    image="ubuntu",
    in_cluster=False,
    cluster_context='docker-desktop',
    config_file = '/usr/local/airflow/include/.kube/config',
    command=["bash", "-c", 'echo "all ok"'],
)
```

I am running Airflow in a Docker Compose setup (using Astronomers CLI). docker-desktop uses `https://kubernetes.docker.internal:6443` as the server endpoint, which was reachable from inside the airflow container.

KubernetesBatchJob Library Version:
0.2.12

**To Reproduce**
1. Start a kubernetes cluster on docker-desktop
2. Create a DAG with the kubernetes batch job operator (see above). 
3. Trigger DAG (e.g. via Airflow UI)
4. Check Logs of Task
4. See stack trace

**Desktop:**
 - OS: MacOs

**Comment by LamaAni** [comment]
Hi, 

Thank you for posting your error.
I will be investigating the error locally.

--- UPDATE

**Error reproduced**

Notes:
1. Steps are non specific to docker desktop.
1. Reproduced on both GCP and docker desktop.

**Comment by LamaAni** [comment]
Blokeje5 please see correction PR here. I will wait a bit before merging it so you would have time to respond. 

Thank you again for your error, it has to do with custom path config files. 

PR: https://github.com/LamaAni/KubernetesJobOperator/pull/8/files

**Comment by Blokje5** [comment]
The PR looks good to me, thanks for reacting and picking it up so quickly!

**Comment by LamaAni** [comment]
Hi,
Than you for reporting!

See new release here: https://github.com/LamaAni/KubernetesJobOperator/releases/tag/0.2.13

If you decide to use/are using this repo, I would love to hear about how it is doing, and what issues you have. 

Also, If you are interested in this project you might wanna check out this one: 
https://github.com/LamaAni/zairflow - Its a docker image and helm/docker-compose implementations to deploy airflow, the kubernetes job operator is built in.

(I am also fishing for starts at this point :) )

Best
LamaAni

**Comment by LamaAni** [comment]
Hi, been a while. If you can add a testimonial, that would be fantastic. Here: #40
